# Generated by Django 2.2.12 on 2021-01-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20210122_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isactive',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
