# Generated by Django 2.2.12 on 2021-01-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='作家姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Wife_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='妻子姓名')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oto.Author_test')),
            ],
        ),
        migrations.RemoveField(
            model_name='wife',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Wife',
        ),
    ]
